// Generated by gencpp from file ur_arm/SetDigitalOut.msg
// DO NOT EDIT!


#ifndef UR_ARM_MESSAGE_SETDIGITALOUT_H
#define UR_ARM_MESSAGE_SETDIGITALOUT_H

#include <ros/service_traits.h>


#include <ur_arm/SetDigitalOutRequest.h>
#include <ur_arm/SetDigitalOutResponse.h>


namespace ur_arm
{

struct SetDigitalOut
{

typedef SetDigitalOutRequest Request;
typedef SetDigitalOutResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDigitalOut
} // namespace ur_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ur_arm::SetDigitalOut > {
  static const char* value()
  {
    return "a259c36a856871635403442ff20cd9c6";
  }

  static const char* value(const ::ur_arm::SetDigitalOut&) { return value(); }
};

template<>
struct DataType< ::ur_arm::SetDigitalOut > {
  static const char* value()
  {
    return "ur_arm/SetDigitalOut";
  }

  static const char* value(const ::ur_arm::SetDigitalOut&) { return value(); }
};


// service_traits::MD5Sum< ::ur_arm::SetDigitalOutRequest> should match 
// service_traits::MD5Sum< ::ur_arm::SetDigitalOut > 
template<>
struct MD5Sum< ::ur_arm::SetDigitalOutRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ur_arm::SetDigitalOut >::value();
  }
  static const char* value(const ::ur_arm::SetDigitalOutRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_arm::SetDigitalOutRequest> should match 
// service_traits::DataType< ::ur_arm::SetDigitalOut > 
template<>
struct DataType< ::ur_arm::SetDigitalOutRequest>
{
  static const char* value()
  {
    return DataType< ::ur_arm::SetDigitalOut >::value();
  }
  static const char* value(const ::ur_arm::SetDigitalOutRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ur_arm::SetDigitalOutResponse> should match 
// service_traits::MD5Sum< ::ur_arm::SetDigitalOut > 
template<>
struct MD5Sum< ::ur_arm::SetDigitalOutResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ur_arm::SetDigitalOut >::value();
  }
  static const char* value(const ::ur_arm::SetDigitalOutResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ur_arm::SetDigitalOutResponse> should match 
// service_traits::DataType< ::ur_arm::SetDigitalOut > 
template<>
struct DataType< ::ur_arm::SetDigitalOutResponse>
{
  static const char* value()
  {
    return DataType< ::ur_arm::SetDigitalOut >::value();
  }
  static const char* value(const ::ur_arm::SetDigitalOutResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UR_ARM_MESSAGE_SETDIGITALOUT_H
