// Generated by gencpp from file ur_arm/SetDigitalOutResponse.msg
// DO NOT EDIT!


#ifndef UR_ARM_MESSAGE_SETDIGITALOUTRESPONSE_H
#define UR_ARM_MESSAGE_SETDIGITALOUTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ur_arm
{
template <class ContainerAllocator>
struct SetDigitalOutResponse_
{
  typedef SetDigitalOutResponse_<ContainerAllocator> Type;

  SetDigitalOutResponse_()
    {
    }
  SetDigitalOutResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetDigitalOutResponse_

typedef ::ur_arm::SetDigitalOutResponse_<std::allocator<void> > SetDigitalOutResponse;

typedef boost::shared_ptr< ::ur_arm::SetDigitalOutResponse > SetDigitalOutResponsePtr;
typedef boost::shared_ptr< ::ur_arm::SetDigitalOutResponse const> SetDigitalOutResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ur_arm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ur_arm': ['/home/zhsyi/vision_servo_zsy/src/ur_arm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ur_arm::SetDigitalOutResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ur_arm/SetDigitalOutResponse";
  }

  static const char* value(const ::ur_arm::SetDigitalOutResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::ur_arm::SetDigitalOutResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetDigitalOutResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ur_arm::SetDigitalOutResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ur_arm::SetDigitalOutResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // UR_ARM_MESSAGE_SETDIGITALOUTRESPONSE_H
